import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import prisma from '../lib/prisma';
import { GetStaticProps } from 'next'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex-Examedi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.row}>
          <div className={styles.col}>
            <div className={styles.pokemon_image}>
              <Image src="/pokemon.png" alt="pokemon" width="100" height="100" />
            </div>
          </div>
          <div className={styles.col}>
          </div>
          <div className={styles.col}>
          </div>
        </div>
      </main>
      export default ({pokemons}) =>
        <ul> 
        {posts.map(post => (
          <li key={post.id}>{post.title}</li>
          ))}
        </ul>
      );
    </div>
  )
}

export default Home
export const getStaticProps: GetStaticProps = async (context) => {
  const pokemons = await prisma.pokemon.findMany();
  return { props: { pokemons } };
}