import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from "@prisma/client";
import { GetStaticProps } from 'next'
import Card from '../components/card'

const prisma = new PrismaClient();

const Home: NextPage = (props) => {
  const pokemons = props.pokemons;
  return (
    <div className={styles.container}>
      <Head>
        <title>Pokedex-Examedi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      {pokemons?.map((pokemon, i) => (
          <Card pokemon={pokemon}/>
          )
        )
      }
      </main>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  const allPokemons = await prisma.pokemon.findMany({
    take: 12,
  });
  return { 
    props: { 
      pokemons: allPokemons, 
    }, 
  };
}

export default Home;